### ISSUE TITLE
「オブリタレーションモード」の追加

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FreeMCOM/freemcom4airsoft#13]
```
BF4の「オブリタレーション」ルールに相当するゲームが出��
�るように、
・キースイッチを2つ追加し、鍵をそれぞれのフラッグの下�
��置く
・従来の「ラッシュ」モードと、「オブリタレーション」��
�ードの切り替えスイッチを追加する

これによりゲームに幅が出てくるかと思います。
```

Original issue reported on code.google.com by `sambar.f...@gmail.com` on 3 Mar 2015 at 2:08

**Comment by sambar-fgfs** [comment]
「オブリタレーション」モードの追加作業が(一応)完了したため、add-obliterationブランチをmasterに統合し、add-obliterationブランチを削除しました。
